In [1]:
import tensorflow as tf

/home/faiz/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.5.0


In [3]:
hello=tf.constant("Hello")

In [4]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
world=tf.constant("world")

In [6]:
world

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [10]:
with tf.Session() as sess:
    result=sess.run(hello+world)

In [11]:
print(result)

b'Helloworld'


In [12]:
a=tf.constant(10)

In [13]:
b=tf.constant(20)

In [14]:
with tf.Session() as sess:
    result=sess.run(a+b)

In [15]:
print(result)

30


In [16]:
const=tf.constant(10)

In [19]:
fillmat=tf.fill((4,4),10)

In [20]:
myzeros=tf.zeros((4,4))

In [23]:
myones=tf.ones((4,4))

In [24]:
mrandn=tf.random_normal((4,4),mean=0,stddev=1)

In [26]:
mrandu=tf.random_uniform((4,4),minval=0,maxval=1)

In [27]:
sess=tf.InteractiveSession()
myops=[const,fillmat,myzeros,myones,mrandn,mrandu]


In [28]:
for op in myops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.6597062  -2.2613845   0.9577602  -0.53787786]
 [-1.1999345  -1.2937307  -0.67710334 -0.64771533]
 [ 0.3561038  -0.44270724  0.16723305  0.3721774 ]
 [ 0.82883644 -1.3940874  -1.1227037   0.44499874]]


[[0.260944   0.11289954 0.8490573  0.03984833]
 [0.7880062  0.7842798  0.12539518 0.70778143]
 [0.9956317  0.83902025 0.07273185 0.81124854]
 [0.9785569  0.32292736 0.58124006 0.4099847 ]]




In [29]:
a=tf.constant([ [1,2],
                    [3,4] ])

In [30]:
b=tf.constant([ [10] ,[100] ])

In [31]:
result=tf.matmul(a,b)

In [32]:
sess.run(result)

array([[210],
       [430]], dtype=int32)